version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdatabase
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
